import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const checkinStyles = StyleSheet.create({
  content: {
    gap: spacing.xl,
    paddingBottom: 144,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xl,
  },
  detailContent: {
    gap: spacing.lg,
    paddingBottom: 144,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xl,
  },
  sectionBlock: {
    gap: spacing.md,
  },
  homeHeroSection: {
    marginBottom: spacing.lg,
  },
  projectSectionBlock: {
    marginBottom: spacing.xl,
  },
  heatmapSectionBlock: {
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  hero: {
    backgroundColor: colors.surface,
    borderRadius: radius.xxl,
    gap: spacing.lg,
    padding: spacing.xl,
    ...shadow,
  },
  heroTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 30,
  },
  heroMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  heroMetrics: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  metricCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  metricValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 26,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heatmapHeader: {
    marginTop: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  projectGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.lg,
  },
  projectCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xxl,
    borderWidth: 1,
    minHeight: 150,
    padding: spacing.md,
    width: '48.5%',
    ...shadow,
  },
  projectCardDone: {
    borderWidth: 1.5,
  },
  projectIcon: {
    alignItems: 'center',
    borderRadius: radius.lg,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  projectEmoji: {
    fontSize: 20,
  },
  projectTitle: {
    color: colors.text,
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  projectCount: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 32,
    marginTop: spacing.lg,
  },
  projectSub: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  quickButton: {
    alignItems: 'center',
    borderRadius: radius.full,
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    width: 42,
  },
  heatmapCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xxl,
    gap: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    ...shadow,
  },
  heatmapCardCompact: {
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  heatmapTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  heatmapTitleRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  heatmapTitle: {
    color: colors.text,
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  heatmapCount: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  heatmapGrid: {
    flexDirection: 'row',
    gap: 4,
  },
  heatmapWeek: {
    gap: 4,
  },
  heatCell: {
    borderRadius: 3,
    height: 10,
    width: 10,
  },
  empty: {
    backgroundColor: colors.surface,
    borderRadius: radius.xxl,
    gap: spacing.sm,
    padding: spacing.xl,
    ...shadow,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  detailHero: {
    backgroundColor: colors.surface,
    borderRadius: radius.xxl,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
    ...shadow,
  },
  detailHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
  },
  detailIcon: {
    alignItems: 'center',
    borderRadius: radius.xl,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  detailEmoji: {
    fontSize: 26,
  },
  detailTitleBlock: {
    flex: 1,
    gap: spacing.xs,
  },
  detailTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  detailQuickAction: {
    alignItems: 'center',
    borderRadius: radius.full,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  detailStats: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  detailStatCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  detailStatValue: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
  },
  detailStatLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  detailSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  detailHeatmapBlock: {
    marginTop: spacing.xl,
  },
  detailMissing: {
    flex: 1,
    gap: spacing.lg,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  recordRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 66,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadow,
  },
  recordDot: {
    borderRadius: radius.full,
    height: 10,
    width: 10,
  },
  recordMain: {
    flex: 1,
    gap: 2,
  },
  recordDate: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 23,
  },
  recordMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  recordStatusPill: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
  },
  recordStatusText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
  recordDelete: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  fab: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.xl,
    bottom: 96,
    height: 64,
    justifyContent: 'center',
    position: 'absolute',
    right: 24,
    width: 64,
    zIndex: 50,
    ...shadow,
  },
  formActions: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  editorContent: {
    gap: spacing.lg,
    paddingBottom: 84,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xl,
  },
  editorPreviewCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.xxl,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.lg,
    ...shadow,
  },
  editorSection: {
    gap: spacing.sm,
  },
  editorOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  editorIconOption: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  editorColorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  editorColorOption: {
    alignItems: 'center',
    borderColor: 'transparent',
    borderRadius: radius.full,
    borderWidth: 2,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  editorColorOptionActive: {
    borderColor: colors.text,
  },
  colorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  colorDot: {
    borderRadius: radius.full,
    height: 34,
    width: 34,
  },
});
